stages:
  - "test"

variables:
  UV_VERSION: "0.9.17"
  PYTHON_VERSION: "3.13"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

.test-template:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  tags:
    - kubernetes-runner
    - docker-runner
  except:
    - tags
  before_script:
    - uv sync --locked --all-extras --dev

formatter:
  extends:
    - .test-template
  script:
    - uv run ruff-format -a

ruff:
  extends:
    - .test-template
  script:
    - uv run ruff {{cookiecutter.project_name}} tests

mypy:
  extends:
    - .test-template
  script:
    - uv run mypy {{cookiecutter.project_name}} tests

