version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      {{cookiecutter.project_name | upper}}_RELOAD: "True"

  {%- if cookiecutter.enable_taskiq == "True" %}

  taskiq-worker:
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    command:
      - taskiq
      - worker
      - {{cookiecutter.project_name}}.tkq:broker
      - --reload
  {%- endif %}
