name: Testing {{cookiecutter.project_name}}

on: push

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - ruff-format
          - ruff
          - mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
      - name: Install deps
        run: uv sync
      - name: Run lint check
        run: uv run pre-commit run -a {{ '${{' }} matrix.cmd {{ '}}' }}
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env
        run: touch .env
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Update docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.28.0"
      - name: run tests
        run: docker-compose run --rm api pytest -vv
