name: Testing {{cookiecutter.project_name}}

on: push

jobs:
  lint:
    strategy:
      matrix:
        include:
          - name: Ruff format
            cmd: ruff format
          - name: Ruff check
            cmd: ruff check {{cookiecutter.project_name}} tests
          - name: Mypy
            cmd: mypy {{cookiecutter.project_name}} tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.17'
          python-version: '3.13'
          enable-cache: "auto"

      - name: Install deps
        run: uv sync --locked --all-groups

      - name: Run lint check
        run: uv run {{ '${{' }} matrix.cmd {{ '}}' }}

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create .env
        run: touch .env

      - name: Update docker-compose
        uses: docker/setup-compose-action@v1

      - name: run tests
        run: docker compose run --rm api pytest -vv

