"""Added users models.

Revision ID: 8caca4abd7b4
{%- if cookiecutter.add_dummy == 'True' %}
Revises: 2b7380507a71
{%- else %}
Revises: 819cbf6e030b
{%- endif %}
Create Date: 2026-05-05 14:37:30.629187

"""

import sqlalchemy as sa
from alembic import op
import fastapi_users_db_sqlalchemy.generics
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "8caca4abd7b4"
down_revision = "2b7380507a71"
{%- if cookiecutter.add_dummy == 'True' %}
down_revision = "2b7380507a71"
{%- else %}
down_revision = "819cbf6e030b"
{%- endif %}
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
