name: Release docker image

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get current tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        cache-from: s3rius/fastapi_template:latest
        tags: |
          s3rius/fastapi_template:latest
          s3rius/fastapi_template:${{steps.tag.outputs.tag}}
